[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "computer-use-ootb-internal"
version = "0.0.40"
description = "Computer Use OOTB"
authors = [{ name = "Siyuan Hu", email = "siyuan.hu.sg@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=23.2.1",
    "annotated-types>=0.7.0",
    "anthropic",
    "anyio>=4.8.0",
    "certifi>=2024.12.14",
    "charset-normalizer>=3.4.1",
    "click>=8.1.8",
    "Cython>=3.0.11",
    "distro>=1.9.0",
    "fastapi>=0.115.7",
    "ffmpy>=0.5.0",
    "filelock>=3.17.0",
    "fsspec>=2024.12.0",
    "gradio>=5.14.0",
    "gradio_client>=1.6.0",
    "h11>=0.14.0",
    "httpcore>=1.0.7",
    "httpx>=0.28.1",
    "huggingface-hub>=0.27.1",
    "idna>=3.10",
    "Jinja2>=3.1.5",
    "jiter>=0.8.2",
    "markdown-it-py>=3.0.0",
    "MarkupSafe>=2.1.5",
    "mdurl>=0.1.2",
    "mpmath>=1.3.0",
    "networkx>=3.4.2",
    "numpy>=2.2.2",
    "orjson>=3.10.15",
    "packaging>=24.2",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "pydantic>=2.10.6",
    "pydantic_core>=2.27.2",
    "pydub>=0.25.1",
    "Pygments>=2.19.1",
    "python-dateutil>=2.9.0.post0",
    "python-multipart>=0.0.20",
    "pytz>=2024.2",
    "PyYAML>=6.0.2",
    "regex>=2024.11.6",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "ruff>=0.9.3",
    "safehttpx>=0.1.6",
    "safetensors>=0.5.2",
    "screeninfo>=0.8.1",
    "semantic-version>=2.10.0",
    "shellingham>=1.5.4",
    "six>=1.17.0",
    "sniffio>=1.3.1",
    "starlette>=0.45.3",
    "sympy>=1.13.1",
    "tokenizers>=0.21.0",
    "tomlkit>=0.13.2",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "tqdm>=4.67.1",
    "transformers>=4.48.1",
    "typer>=0.15.1",
    "typing_extensions>=4.12.2",
    "tzdata>=2025.1",
    "urllib3>=2.3.0",
    "uvicorn>=0.34.0",
    "websockets>=14.2",
    "pyautogui>=0.9.54",
    "dashscope>=1.22.1",
    "qwen_vl_utils>=0.0.9",
    "boto3>=1.33.1",
    "litellm",
    "opencv-python",
    "easyocr",
    "matplotlib",
    "fastapi",
    "uvicorn",
    "uiautomation",
    "pydantic",
    "pywinauto"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.6.7",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.23.6",
]

[tool.hatch.build.targets.wheel]
packages = ["src/computer_use_ootb_internal"]
include = ["src/computer_use_ootb_internal/**/*"]  # This ensures all subpackages are included

[project.scripts]
computer-use-ootb-internal = "computer_use_ootb_internal.app_teachmode:main"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.hatch.metadata]
allow-direct-references = true