[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ak-tool"
version = "0.1.4"
description = "Consolidates AWS MFA login, Kubernetes context switching, and Kubernetes API token refreshing into one simple CLI tool."
authors = [
  { name = "Aharon Haravon", email = "aharon.haravon@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

# Dependencies (installed automatically with pip install . or flit install)
dependencies = [
  "boto3",
  "pyyaml",
  "pytest",
  "requests",
  "click >=8.1",
  "python-crontab",
]

[project.optional-dependencies]
dev = [
  "flake8",
  "black",
  "pytest-cov",
  "mypy",
  "flit",
  "sphinx",
  "docformatter",
  "bump2version",
]

[project.scripts]
ak = "ak_tool.cli:main"
