[build-system]
requires = ["setuptools>=61.0", "PyYAML>=6.0.2", "matplotlib>=3.10.0", "sympy>=1.13.3", "numpy>=2.2.2", "scipy>=1.15.1", "tqdm>=4.67.1", "seaborn>=0.13.2"]
build-backend = "setuptools.build_meta"

[project]
name = "odeestimatorpy"
version = "2025.0.8"
authors = [
  { name="Nahomi Bouza", email="nahomi.bouza@gmail.com" },
]
description = "ODE Estimator is a project designed to model and estimate parameters of systems of ordinary differential equations (ODEs)."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/NahomiB/ode-estimator"
Wiki = "https://github.com/NahomiB/ode-estimator/wiki"

[tool.setuptools.packages.find]
where = ["."]
include = ["odeestimatorpy*"]