[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "make87_messages"
version = "0.0.82"
authors = [
  { name = "Nisse Knudsen", email = "nisse@make87.com" },
]
dependencies = [
  "protobuf",
]
readme = "README.md"
requires-python = ">=3.9,<3.13"

[tool.setuptools.packages.find]
include = ["make87_messages", "make87_messages.*"]

[project.optional-dependencies]
dev = [
  "pre-commit",
]
