[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AirTrafficSim"
version = "0.2.0-alpha.3"
authors = [
    { name = "Frankie Hui", email = "kyhuiaf@connect.ust.hk" },
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]
description = "A lightweight collection of tools for air traffic management research."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
keywords = ["air transportation", "atm", "simulations", "visualisation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]
dependencies = [
    "annotated-types>=0.7.0",
    "numpy>=2.2.0",
]

[project.urls]
Repository = "https://github.com/HKUST-OCTAD-LAB/AirTrafficSim"

[project.optional-dependencies]
polars = [
    "polars[calamine]>=1.18.0",
]
networking = [
    "httpx[http2]>=0.28.1",
]
era5 = [
    "xarray>=2024.11.0",
]
jax = [
    "jax>=0.5.0",
]
plot = [
    "matplotlib>=3.10.0",
]
all = [
    "airtrafficsim[polars,networking,era5]",
]

[dependency-groups]
dev = [
    "array-api-strict>=2.2",
    "ipykernel>=6.29.5",
    "mypy>=1.13.0",
    "ruff>=0.8.3",
    "types-pytz>=2024.2.0.20241221",
]
test = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.4",
    "anyio>=4.7.0",
]
docs = [
    "griffe-warnings-deprecated>=1.1.0",
    "mkdocs-material[imaging]>=9.5.49",
    "mkdocstrings-python>=1.13.0",
]


[tool.uv]
default-groups = ["dev", "test", "docs"]

[tool.ruff]
lint.select = [
    "E",
    "W",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "NPY", # numpy
    # "PD",  # pandas
    "DTZ", # flake8-datetimez
    "RUF",
]
line-length = 80
target-version = "py310"

[tool.ruff.lint.isort]
known-first-party = ["numpy", "pandas"]

[tool.mypy]
python_version = "3.10"
platform = "posix"
color_output = true
pretty = true
show_column_numbers = true
strict = true
check_untyped_defs = true
ignore_missing_imports = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
