[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geospatial-analysis-environment"
version = "0.1.7"
requires-python = '>=3.11'
readme = "README.md"
description = "Geospatial analysis environment."
authors = [
    { name = "Chris Lowrie", email = "lowriechris779@gmail.com" }
]
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent'
]
license = { text = "MIT" }
dependencies = [
    "xarray",
    "pandas",
    "geopandas",
    "fiona",
    "numpy",
    "rioxarray",
    "rasterio",
    "h5netcdf",
    "matplotlib",
    "google-cloud-storage",
    "pytest",
    "s2sphere",
    "fastparquet",
    "pyarrow",
    "zarr",
    "fsspec",
    "gcsfs",
    "odc-geo",
    "numba==0.60.0",
    "xarray-spatial",
    "s2sphere",
    "pytest",
    "tqdm",
    "memory_profiler",
    "joblib",
    "gdal>=3.10.0"
]

[tool.uv.sources]
geospatial-analysis-environment = { workspace = true }
