[tool.poetry]
name = "rspyredis"
version = "0.1.1"
description = "A light python package for redis management."
authors = ["Reza Shirazi <itreza7@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/itreza7/rspyredis"

[tool.poetry.dependencies]
python = "^3.11"
redis = "^5.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^23.1"
flake8 = "^5.0"
isort = "^5.10"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
