[project]
name = "tigol"
version = "0.0.3"
authors = [
  { name="Alessio D'Ambrosio", email="alessio.dambrosio@tigol.net" },
]
description = "A package for communicating with TIgol."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/alessiodam/TIgol-python"
Issues = "https://github.com/alessiodam/TIgol-python/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tigol"]
