[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "carmen_cloud_client"
version = "1.3.0"
authors = [
  { name="Botond BALÃZS", email="botond.balazs@arip.hu" },
]
description = "Python client for Carmen Cloud by Adaptive Recognition. Efficiently read license plates, recognize vehicle details, and process container, railway wagon, and US DOT codes."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.31.0",
    "requests_toolbelt>=1.0.0",
    "pydantic>=1.10.9",
    "urllib3>=2.0.3",
]

[project.urls]
"Homepage" = "https://github.com/adaptiverecognition/python-carmen-cloud-client"
"Bug Tracker" = "https://github.com/adaptiverecognition/python-carmen-cloud-client/issues"

[[tool.pydoc-markdown.loaders]]
type = "python"
search_path = [ "./carmen_cloud_client" ]
