[project]
name = "shared-package-lentinis"
version = "1.0.26"
description = "A shared utilities package"
dependencies = ["fastapi"]

[build-system]
requires = ["setuptools", "wheel","twine"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]


