[tool.poetry]
name = "riskoptima"
version = "1.14.0"
description = "The RiskOptima toolkit is a comprehensive Python solution designed to assist investors in evaluating, managing, and optimizing the risk of their investment portfolios. This package implements advanced financial metrics and models to compute key risk indicators, including Value at Risk (VaR), Conditional Value at Risk (CVaR), and volatility assessment"
authors = ["Jordi Corbilla <jordi.coll.corbilla@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/JordiCorbilla/RiskOptima"
repository = "https://github.com/JordiCorbilla/RiskOptima"
keywords = ["portfolio", "risk", "optimization", "VaR", "backtesting", "monte-carlo", "machine-learning", "random-forest", "linear-regression", "gradient-boosting", "mean-variance", "black-litterman"]

[tool.poetry.dependencies]
python = ">=3.11"
numpy = ">=1.26.4"
pandas = ">=2.1.4"
scipy = ">=1.13.1"
statsmodels = ">=0.14.2"
yfinance = ">=0.2.51"
matplotlib = ">=3.8.4"
scikit-learn = ">=1.5.1"
xgboost = ">=2.1.3"
seaborn = ">=0.13.2"
squarify = ">=0.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



