[project]
name = "google_internal_apis"
version = "0.3.1"
description = "A wrapper around various internal (and undocumented) Google APIs that use grpc and json protobufs."
authors = [
    {name = "Elliana May", email = "me@mause.me"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.10"
readme = "README.md"
dependencies = [
    "ghunt>=0.1",
]

[project.urls]
repository = "https://github.com/Mause/gbooks-upload"

[tool.setuptools.packages]
find = { include = ["google_internal_apis"] }

[dependency-groups]
dev = [
    "jinja2>=3.1.5",
    "mypy>=1.14.1",
    "pdbpp<1.0.0,>=0.10.3",
    "pre-commit<4.0.0,>=3.4.0",
    "pudb>=2024.1.3",
    "types-httplib2>=0.22.0.20241221",
    "types-requests>=2.32.0.20241016",
]

[tool.ruff.lint]
select = ["I", "E", "W", "F", "C", "R"]

[tool.uv]
package = true

[tool.uv.sources]
google-internal-apis = { path = "google_internal_apis" }

[tool.mypy]
ignore_missing_imports = true
