[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neutools"
version = "0.2.3"
description = "neutron panel debug tools"
authors = [{ name = "cxykevin", email = "cxykevin@yeah.net" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: POSIX :: Linux",
]
dependencies = ["typer"]

[project.urls]
homepage = "https://gitee.com/cxy_kevin/neutron"
repository = "https://gitee.com/cxy_kevin/neutron"

[project.scripts]
neutools = "neutools.__main__:app"
neu = "neutools.__main__:app"

[tool.setuptools]
include-package-data = true
