[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flow-modnum"
version = "0.0.14"
description = "Flow Hydro Consulting's numerical modeling group Python library."
readme = "README.md"
authors = [{ name = "Matias Bravo", email = "mjbravo4@uc.cl" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["numerical", "modeling"]
dependencies = [
    "numpy >= 1.26.4",
    "pandas >= 2.2.2",
    "matplotlib >= 3.8.4",
    "folium >= 0.18.0",
    "plotly >= 5.22.0",
    "pyproj >= 3.6.1",
    "tqdm >= 4.66.4",
    "geopandas >= 1.0.1",
]
requires-python = ">=3.12.4"

[tool.setuptools.package-data]
flow_modnum = ["exe/*.exe"]  # Incluye los ejecutables en la carpeta bin

[project.urls]
Homepage = "https://github.com/MatiasBravo1511/flow-modnum"