[project]
name = "Neurotorchmz"
version = "25.2.1"
authors = [
  { name="Andreas Brilka"},
]

description = "Neurotorch is a tool designed to extract regions of synaptic activity in neurons tagges with iGluSnFR, but is in general capable to find any kind of local brightness increase due to synaptic activity"
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"

classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing"
]
keywords = ["neurotorch", "neurons", "glutamate", "synapses", "python", "iGluSnFR"]

dependencies = [
  "numpy>=2.1.2",
  "pandas>=2.2.3",
  "scipy>=1.14.1",
  "matplotlib>=3.9.2",
  "scikit-image>=0.24.0",
  "xarray>=2024.9.0",
  "pims>=0.7",
  "pyimagej==1.5.0",
  "psutil",
  "fsspec>=2024.9.0",
  "requests>=2.32.3",
  "platformdirs>=4.3.6",
  "tkinter-tooltip"
]


[project.urls]
Homepage = "https://github.com/andreasmz/neurotorch"
Repository = "https://github.com/andreasmz/neurotorch"
Issues = "https://github.com/andreasmz/neurotorch/issues"
Documentation = "https://andreasmz.github.io/neurotorch/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dev",
  "/build",
  "/dist",
  "/docs",
]