[build-system]
requires = ["setuptools", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "dccXMLJSONConv"
version = "3.0.0.dev3"
description = "Python module for converting XML DCC (https://www.ptb.de/dcc/) to JSON and vice versa"
authors = [{name = "Benedikt Seeger,Thomas Bruns, Vanessa Stehr", email = "benedikt.seeger@ptb.de"}]
license = {text = "LGPL-2.1-or-later"}
requires-python = ">=3.8"
dependencies = [
    "jinja2",
    "lxml",
    "xmlschema"
]
readme = {file = "README.md", content-type = "text/markdown"}

[project.optional-dependencies]
web = [
    "fastapi",
    "uvicorn"
]
dev = [
    "pytest",
    "pytest-cov",
    "mypy",
    "black",
    "build",
    "httpx"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dccXMLJSONConv" = ["data/**/*", "schemata/**/*"]
