[project]
name = "cursedtodo"
description = "Cursedtodo is a TUI todo manager written in Python using (n)curses library"
authors = [
    { name = "François Lachèse", email = "francois.lachese@gmail.com" },
]
dependencies = [
    "ics>=0.7.2,<0.8",
]
requires-python = ">=3.12"
readme = "README.md"
dynamic = []
version = "0.0.1rc10"

[project.license]
text = "MIT"

[project.scripts]
ctodo = "cursedtodo.cursedtodo:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
package-dir = "src"
distribution = true

[tool.pdm.version]
source = "scm"

[tool.pdm.scripts]
debug = "python -m debugpy --listen 127.0.0.1:5678 --wait-for-client -m cursedtodo.cursedtodo"

[tool.mypy]
mypy_path = "src/"
strict = true
overrides = [
    { module = "ics.*", ignore_missing_imports = true },
]

[dependency-groups]
dev = [
    "debugpy>=1.8.11",
]
