[tool.poetry]
name = "davidkhala.gcp"
version = "0.4.0"
description = "Core gcp components"
authors = ["David Liu <david-khala@hotmail.com>"]
readme = "README.md"
packages = [{ include = "davidkhala" }]

[tool.poetry.dependencies]
python = "^3.10"
google-auth = { version = "*", extras = ['requests'] }
google-api-core = "*"
google-cloud-core = { version = "*", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "*"
google-cloud-language = "*"

[tool.poetry.extras]
core = ["google-cloud-core"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
