[tool.poetry]
name = "django-firebase-auth-sdk"
version = "0.1.3"
description = "Django 사용자 인증을 위한 Firebase 통합"
authors = ["94wogus <94wogus@gmail.com>"]
readme = "README.md"
packages = [
    { include = "django_firebase_auth" }
]

[tool.poetry.dependencies]
python = "^3.12"
django = ">=5.1,<6.0"
firebase-admin = ">=6.3,<7.0"
graphql-core = ">=3.1,<3.3"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 100
target-version = ["py312"]
exclude = """
(
    .venv
    | venv
    | dist
    | migrations
)
"""

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
skip =  [".venv", "venv", "dist", "migrations"]