[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oeva"
version = "1.0.8"
authors = [
    { name="Kareem Elbahrawy", email="kareem.elbahrawy@gmail.com" },
]
description = "Eva - A friendly AI assistant for managing your projects"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openai>=1.0.0",
    "python-dotenv>=0.19.0",
    "pydantic>=2.0.0",
    "rich>=10.0.0",
    "typer>=0.9.0"
]

[project.urls]
"Homepage" = "https://github.com/kelbahrawy/eva"
"Bug Tracker" = "https://github.com/kelbahrawy/eva/issues"

[project.scripts]
oeva = "oeva.eva:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["oeva*"]

[tool.setuptools.package-data]
"oeva" = ["config/*.yaml", "config/*.json"] 