repos:

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.6'
    hooks:
      - id: bandit
        language_version: python3
        #~ exclude: api/config/test_config.py
        #~ exclude: api/core/test_core.py
        #~ args: ["--skip", "B101", "-exclude", "api/config/test_config.py,api/core/test_core.py"]
        args: ["--exclude", "api/config/test_config.py,api/core/test_core.py"]


# https://github.com/Yelp/detect-secrets
-   repo: git@github.com:Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        #exclude: .*/tests/.*, .*/package-lock.json, .*/yarn.lock
        exclude: .*/yarn.lock|.*/package-lock.json


- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
