[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meteoalarm"
version = "0.1.2"
description = "A Python library for accessing MeteoAlarm weather warnings"
authors = [{name = "Niklas Jordan", email = "hello@niklasjordan.com"}]
license = {file = "LICENSE"}
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.0",
    "pyyaml>=5.1",
    "pytz>=2021.1"
]

[tool.setuptools.package-data]
"meteoalarm.assets" = ["*.yaml", "*.json"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["meteoalarm*"]

[tool.pytest]
pythonpath = "src"

[project.urls]
Homepage = "https://github.com/NiklasJordan/meteoalarm"
