[tool.poetry]
name = "steev"
version = "0.1.2"
description = "steev cli"
authors = [
    "SangUk Park <psycoder@steev.io>",
    "Sungman Cho <sungman@steev.io>"
]
readme = "README.md"
homepage = "https://steev.io"
repository = "https://github.com/TBD-Labs/steev-cli"
keywords = ["steev", "ml", "ai", "agent", "experiment", "automation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
packages = [
    { include = "src" }
]
exclude = ["src/settings/dev.py"]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.8"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
pyyaml = "^6.0.2"
pyjwt = "^2.10.1"
websocket-client = "^1.8.0"
pydantic = "^2.10.5"

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
ruff = "^0.6.9"
pre-commit = "^4.0.0"
types-requests = "^2.32.0.20241016"
types-pyyaml = "^6.0.12.20241230"

[tool.poetry.group.language]
optional = true

[tool.poetry.group.language.dependencies]
peft = "^0.14.0"
accelerate = "^1.3.0"
datasets = "^3.2.0"
transformers = "^4.48.1"
trl = "^0.13.0"
bitsandbytes = {version = "^0.45.1", markers = "platform_system == 'Linux'"}

[tool.poetry.scripts]
steev = "src.cli:cli"

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.mypy]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
