[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pankaj_core"
version = "0.0.2"
authors = [
  { name="Pankaj Pratap Singh", email="pankajsys.engg@gmail.com" },
]
description = "A example package for test"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/pankajps/pankaj_core"
Issues = "https://github.com/pankajps/pankaj_core/issues"
