[tool.poetry]
authors = ["Niko Ehrenfeuchter <nikolaus.ehrenfeuchter@unibas.ch>"]
description = "Metrics collector and exporter to monitor file sizes and ages."
include = [
   { path = "resources/run-metrics-exporter.sh", format = ["sdist", "wheel"] },
   { path = "resources/systemd/fsa-metrics.service", format = ["sdist", "wheel"] },
]
license = "GPL-3.0-or-later"
name = "file-size-age-metrics"
readme = "README.md"
version = "0.0.1-a.7"

packages = [{include = "fsa_metrics", from = "src"}]

homepage = "https://pypi.org/project/file-size-age-metrics/"
keywords = ["prometheus", "metrics", "file-metrics"]
repository = "https://github.com/imcf/file-size-age-metrics"

[tool.poetry.urls]
# "Changelog" = "https://github.com/imcf/file-size-age-metrics/blob/main/CHANGELOG.md"
"Organisation Homepage" = "https://imcf.one/"

[tool.poetry.dependencies]
PyYAML = "^6.0"
click = "^8.1.3"
loguru = "^0.7.0"
prometheus-client = "^0.21.1"
python = "^3.9"
python-box = "^7.3.2"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pylint = "^2.15.5"
pdoc = "^15.0.1"

[tool.poetry.scripts]
fsa-metrics = "fsa_metrics.cli:run_fsa_exporter"

[tool.poetry-dynamic-versioning]
enable = false
style = "semver"
vcs = "git"

[tool.poetry-dynamic-versioning.substitution]
folders = [
  {path = "src"},
]

[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
