site_name: pydykit - A Python-based Dynamics toolKIT
site_url: https://pydykit.github.io/pydykit/
repo_url: https://github.com/pydykit/pydykit # TODO: Check this link when deployed
nav:
  - About: index.md
  - Getting Started: getting_started.md
  - Examples:
      - Pendulum 3D: examples/pendulum_3d.md
      - Lorenz System: examples/lorenz.md
      - Chemical Reactor: examples/reactor.md
      - List examples: examples/list.md
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png # TODO: Check this when deployed
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: custom
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom
      accent: custom
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.tabs
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://pydykit.github.io/pydykit
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pydykit/pydykit # TODO: Check this
  generator: false
  version:
    provider: mike # TODO: Check this when deployed
plugins:
  - search
  - mkdocstrings
  - markdown-exec
  - macros:
      on_undefined: strict
  - print-site:
      add_to_navigation: true
      add_table_of_contents: true
      toc_depth: 2
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
copyright: Copyright &copy; 2024 - 2025 The authors of pydykit
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      title: Page content
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path:
        - docs
        - pydykit/example_files
  - pymdownx.highlight:
      linenums: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
