[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "corva-otel-faas"
version = "0.2.1rc1"
description = "OpenTelemetry faas instrumentation for Python at corva.ai"
readme = "README.md"
requires-python = ">=3.6"
authors = [
    { name = "Radoslav Kirilov", email = "radoslav.kirilov@corva.ai" },
    { name = "Ivaylo Papratilov", email = "ivaylo.papratilov@corva.ai" }
]
dependencies = [
    "corva-otel-semconv >=0.1.2",
    "opentelemetry-api",
    "opentelemetry-semantic-conventions"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/corva-ai/otel/tree/main/python/faas"

[tool.hatch.envs.default]
dependencies = [
    "pytest",
    "flake8"
]

[tool.hatch.build.targets.sdist]
include = [
  "src/corva_otel",
]

[tool.hatch.build.targets.wheel]
packages=["src/corva_otel"]
