[project]
name = "psdist"
authors = [{name = "Austin Hoover"}]
description = "Analysis tools for phase space distributions"
license = {file = "LICENSE"}
readme = "README.md"
version = "2.0.2"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "scipy",
    "tqdm",

    "ipywidgets",
    "matplotlib",
    "seaborn",
    "ultraplot",
]

[project.urls]
repository = "https://github.com/austin-hoover/psdist"

[build-system]
requires = [
    "setuptools>=62",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"
