[build-system]
requires = ["hatchling>=1.10.0", "jupyter_client", ]
build-backend = "hatchling.build"

[project]
name = "clang_repl"
dynamic = ["version"]
description = "IPython kernel forwarding C++ cells to clang-repl"
readme = "README.md"
license = { text = "no license" }
authors = [ { name = "Paul Manstetten", email = "paul.manstetten@tuwien.ac.at" }, ]

requires-python = ">=3.11"
dependencies = [ "ipykernel", "pexpect", "notebook", "jupyter-console",]

[project.urls]
Homepage = "https://github.com/pmanstet/clang_repl_kernel.git"

[tool.hatch.version]
path = "clang_repl/__init__.py"

# Used to call hatch_build.py
[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.sdist]
include = [ "/clang_repl", ]

[tool.hatch.build.targets.wheel.shared-data]
"data_kernelspec/share" = "share"
