[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "boomba"
version = "0.1.0b2"
description = "Light and Fast ETL Framework"
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.12"
authors = [
    { name = "SungEun An", email = "bach0918@gmail.com" }
]
dependencies = [
    "polars",
    "pyarrow",
    "SQLAlchemy"
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
repository = "https://github.com/Baboomba/boomba"

[project.scripts]
boomba = "boomba.main:main"