[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sqldeps"
version = "0.0.3"
description = "SQL Dependency Extractor"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
authors = [
    {name = "CainÃ£ Silva", email = "coutodasilva@wisc.edu"},
    {name = "Matt Christie", email = "mjchristie@wisc.edu"}
]
readme = "README_PyPI.md"
keywords = ["sql", "dependency", "parser", "extractor"]
dependencies = [
    "click>=8.1.8",
    "groq>=0.17.0",
    "loguru>=0.7.3",
    "openai>=1.59.5",
    "pandas>=2.2.3",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
    "sqlalchemy>=2.0.37",
    "sqlparse>=0.5.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.2",
    "twine>=6.1.0",
]
notebook = [
    "ipykernel>=6.29.5",
]

[project.scripts]
sqldeps = "sqldeps.cli:main"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]

[tool.hatch.metadata]
allow-direct-references = false

[tool.hatch.build]
packages = ["sqldeps"]
