[project]
name = "pyspark-polarisx-test"
version = "0.1.2"
description = "Test Polaris Catalog Lib implementation with PySpark"
authors = [{name = "Carl Bruun", email = "carl99@live.dk"}, {name = "Andreas Kongstad", email = "andreaskongstad99@icloud.com"}]
license = {text = "MIT"}  # Match the license used in your LICENSE file
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyspark>=3.5.4",
    "pytest>=8.3.4",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
homepage = "https://github.com/Carlbrr/Polaris_PySpark"

[tool.hatch.build]
include = [
    "polarisx",       # Include the core library directory
    "README.md",      # Include the README
    "LICENSE",        # Include the license file
    "pyproject.toml"  # Include the build configuration
]

exclude = [
    "tests",          # Exclude the tests directory
    "mock_api.py",    # Exclude the mock API
    ".venv",          # Exclude the virtual environment folder
    "*.egg-info",     # Exclude build artifacts
    "dist",           # Exclude built distributions
    "__pycache__",    # Exclude Python cache files
    "*.pyc",          # Exclude compiled Python files
    "*.log",          # Exclude log files
    "*.lock",         # Exclude lock files (like uv.lock)
]