[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "filterutil"
version = "0.0.7"
authors = [
  { name="Andrey Smirnov", email="smirnovcode@mail.ru" },
]
description = "Let you register and use filters in right way"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Operating System :: OS Independent",
]

[project.urls]
"Github repo" = "https://github.com/akvilary/filterutil"
"Bug tracker" = "https://github.com/akvilary/filterutil/issues"
"Release notes in Telegram" = "https://t.me/filterutil"
