  [project]
  name = "dlt-plus"
  version = "0.6.2a1"
  description = "dlt+ is a framework for productionising dlt pipelines in teams and at scale, with support for Iceberg and AI workflows."
  requires-python = ">=3.9,<3.13"
  authors = [
    { name = "dltHub Inc.", email = "services@dlthub.com" },
  ]
  maintainers = [
    { name = "Marcin Rudolf", email = "marcin@dlthub.com" },
    { name = "Adrian Brudaru", email = "adrian@dlthub.com" },
    { name = "Anton Burnashev", email = "anton@dlthub.com" },
    { name = "David Scharf", email = "david@dlthub.com" },
  ]
  classifiers = [
      "Development Status :: 3 - Alpha",
      "Intended Audience :: Developers",
      "Topic :: Software Development :: Libraries",
      "Typing :: Typed",
      "Programming Language :: Python :: 3.9",
      "Programming Language :: Python :: 3.10",
      "Programming Language :: Python :: 3.11",
      "Programming Language :: Python :: 3.12",
      "Operating System :: MacOS :: MacOS X",
      "Operating System :: POSIX :: Linux",
      "Operating System :: Microsoft :: Windows",
    ]
  readme = "README.md"
  license = { file = "LICENSE.md" }
  homepage = "https://github.com/dlt-hub"
  dependencies = [
      "dlt>=1.6.2a0",
      "pyjwt>=2.8.0",
      "cryptography==40.0.2",
  ]
  keywords = [ "etl" ]
  include = [ 
    "LICENSE.txt",
    "README.md",
    "dlt_plus/project/_templates/project/dlt.yml",
    "dlt_plus/project/_templates/project/gitignore",
    "dlt_plus/project/_templates/project/dlt/config.toml",
    "dlt_plus/project/_templates/project/dlt/secrets.toml",
    ]

  [project.optional-dependencies]
  dbt = [
      "jinja2>=3.1.2",
      "pydantic>2",
      "dbt-core<1.9",
  ]
  cache = [
    "duckdb>0.9",
    "sqlglot>=20.0.0"
  ]
  mssql = [
    "sqlalchemy>1.4",
    "pyodbc>=4.0.39",
  ]
  iceberg = [
    "pyiceberg>=0.8.1",
    "pyarrow>=17",
    "sqlalchemy>2",
    "duckdb>=1.1.3",
    "sqlglot>=20.0.0",
  ]

  # [tool.uv.sources]
  # dlt = { path = "../../../dlt", editable = true }
  # dlt = { git = "https://github.com/dlt-hub/dlt.git", rev = "fix/prepare-tables-before-views" }

  # mark as OSS dlt extension
  [project.entry-points.dlt]
  dlt-plus-context = "dlt_plus.plugin"

  # mark as dlt plus package
  [project.entry-points.dlt_package]
  dlt-project = "dlt_plus"
  license-scopes = "dbt_generator sources.mssql project"

  [tool.hatch.build.targets.sdist]
  packages = ["dlt_plus"]

  [tool.hatch.build.targets.wheel]
  packages = ["dlt_plus"]

  [build-system]
  requires = ["hatchling>=1.20.0"]
  build-backend = "hatchling.build"