[project]
name = "mcp_simulator"
version = "0.1.0"
description = "MCP server for lineup and projection simulation tools"
authors = []
dependencies = [
    "mcp>=1.2.0",
    "pandas"
]
requires-python = ">=3.10"

[project.scripts]
uvx = "mcp_simulator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_simulator"]

[tool.uv]
dev-dependencies = ["pyright>=1.1.389"]
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
