[tool.poetry]
name = "fastnetar-db"
version = "0.1.3"
description = ""
authors = ["Samuel Roberts <samuel.roberts@magnetarit.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
libsql-client = "^0.3.1"
passlib = "^1.7.4"
pytest = "^8.3.4"
asyncio = "^3.4.3"
pytest-asyncio = "^0.25.3"
bcrypt = "^4.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
